---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-pvc-01
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc