apiVersion: v1
kind: Pod
metadata:
  name: csi-block-test-pod
  namespace: ceph-csi-rbd
spec:
  containers:
  - name: test-container
    image: registry.k8s.io/busybox:latest
    command: ["/bin/sh", "-c", "echo 'Test container started. Block device /dev/testblock should exist. Listing device:'; ls -l /dev/testblock; echo 'Sleeping for 20 seconds then exiting.'; sleep 20; echo 'Exiting.'"]
    volumeDevices:
      - name: test-storage
        devicePath: /dev/testblock
  volumes:
  - name: test-storage
    persistentVolumeClaim:
      claimName: ceph-pvc-01
  restartPolicy: Never
